import type { Request } from "express";

export type VenmailIntegrationEventType =
  | "EmployeeLogin"
  | "MailReceived"
  | "AppFileCreated"
  | "MailSent"
  | "FollowUpSent"
  | "MailOpened"
  | "MailRead"
  | "ContactAdded"
  | "CampaignCreated"
  | "CampaignSent"
  | "CampaignLinkOpened"
  | "CampaignLinkClicked"
  | "ProspectDiscovered"
  | "SubscriptionRenewed"
  | "SubscriptionExpired"
  | string; // Allow future/custom event types

export interface VenmailIntegrationEventBody<TPayload = Record<string, unknown>> {
  event_type: VenmailIntegrationEventType | string;
  generated_at: string;
  payload: TPayload;
  event_id: number;
  organization_id: number;
  integration_id: number;
  generated_by?: number | null;
}

export interface VenmailIntegrationEvent<TPayload = Record<string, unknown>>
  extends VenmailIntegrationEventBody<TPayload> {
  headers: {
    "x-venmail-event": string;
    "x-venmail-signature": string;
  };
}

export interface VenmailAttachment {
  filename: string;
  content_type?: string;
  size?: number;
  /**
   * Raw base64 content. Venmail typically uploads large attachments to storage and
   * provides a signed URL instead – see `storage_url`.
   */
  content?: string;
  /**
   * Storage URL for large attachments uploaded to Venmail's storage service
   */
  storage_url?: string;
  /**
   * Attachment ID for accessing the attachment via Venmail API
   */
  attachment_id?: string;
  /**
   * Thumbnail URL for preview (generated by Venmail)
   */
  thumbnail_url?: string;
  [key: string]: unknown;
}

export interface VenmailMailWebhookPayload {
  rcpt_to: string;
  to: string | string[];
  from: string;
  /** Sender envelope, if different from `from`. */
  mail_from?: string;
  cc?: string | string[] | null;
  bcc?: string | string[] | null;
  subject?: string;
  date?: string;
  in_reply_to?: string;
  references?: string | string[];
  message_id: string;
  html?: string;
  text?: string;
  summary?: string;
  attachments?: VenmailAttachment[];
  spam_status?: Record<string, unknown> | string | boolean;
  /** Optional Venmail event hint (MessageSent, MessageDelayed, etc.). */
  event?: string;
  [key: string]: unknown;
}

export type VenmailMessageStatus =
  | "MessageDelivered"
  | "MessageDelayed"
  | "MessageDeliveryFailed"
  | "MessageHeld"
  | "MessageBounced"
  | "Success"
  | "Delivered"
  | "SoftFail";

export interface VenmailStatusMessage {
  message_id: string;
  to?: string;
  from?: string;
  tag?: string;
  meta?: Record<string, unknown>;
  [key: string]: unknown;
}

export interface VenmailStatusWebhookPayload {
  status: VenmailMessageStatus | string;
  message: VenmailStatusMessage;
  details?: string;
  output?: string;
  timestamp?: string | number;
  time?: string | number;
  sent_with_ssl?: boolean;
  [key: string]: unknown;
}

export interface VenmailBounceWebhookPayload {
  original_message: VenmailStatusMessage;
  bounce: {
    type?: string;
    reason?: string;
    [key: string]: unknown;
  };
  timestamp?: string | number;
  [key: string]: unknown;
}

export type VenmailKumoLogRecord =
  | VenmailBounceWebhookPayload
  | VenmailStatusWebhookPayload
  | {
      type: string;
      message_id: string;
      sender?: string;
      recipient?: string | string[];
      response?: string;
      meta?: Record<string, unknown>;
      event_time?: string | number;
      timestamp?: string | number;
      [key: string]: unknown;
    };

export interface VenmailWebhookRequest<TBody = unknown> {
  headers: Record<string, string | undefined>;
  req: Request;
  rawBody: Buffer;
  body: TBody;
}
